#!/usr/bin/env python3

from brainflex import flex
# -

class Queue:
	def __init__(self, queue = None):
		self.queue = queue or []
	def pop(self):
		return self.queue.pop()
	def peek(self):
		return self.queue[-1]
	def push(self, value):
		self.queue.insert(0, value)
	def size(self):
		return len(self.queue)
	def __str__(self):
		return str(self.queue)
	def __repr__(self):
		return str(self)
	def output(self):
		print('\n'.join(map(str, self.queue)))

if __name__ == '__main__':
	flex('BrainFlueue', 'Wheat Wizard', 'brainflueue', Queue(), Queue())
